apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-demo
  labels:
    app: hello-world-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-demo
  template:
    metadata:
      labels:
        app: hello-world-demo
    spec:
      containers:
        - name: hello-world-demo
          image: dipakjid/hello-world-demo:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-demo-service
spec:
  type: LoadBalancer
  selector:
    app: hello-world-demo
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 80

