apiVersion: v1
kind: Service
metadata:
  name: hello-world-demo-service
spec:
  type: LoadBalancer
  selector:
    app: hello-world-demo
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 80
